### PR TITLE
Config file containing AZ, MCTS, and database parameters

### PR DESCRIPTION
**Pull request by jlaw9**
Reviving some of the ideas from #47, without the HPC stuff.

Allowing the user to specify parameters used by the policy training, AlphaZero, MCTS rollouts, and the database in a config file, rather than hard-coded in a script, will enable more experimentation such as a systematic parameter search. For example, a user may want to vary the `dirichlet_x` noise parameter over a range and see how that affects the results. 

Another benefit of having all the parameters in a single file is that there are parameters spread throughout classes and functions in the inheritance hierarchy and they can be hard to find for a new user.

Currently this code uses a config file, but runs using default values if a config file is not given. We could also add a function to `run_config.py` that makes command-line arguments for each of the parameters in the config file. 

Part of the motivation for this is to show the ARPA-E folks the flexibility of the software such as running the QED example on eagle `python optimize_qed.py --config config/qed_config_eagle.yaml` vs running locally `python optimize_qed.py --config config/qed_config_local.yaml`.

### CODE REVIEW

**Comment by pstjohn** [comment]
This looks good to me. I think we could probably just delete
https://github.com/NREL/rlmolecule/blob/20210407-run-config/examples/qed/optimize_qed.py#L39-L43? Probably leftover from when we did other initialization.

**Comment by jlaw9** [comment]
Don't we need those lines to initialize MoleculeTFAlphaZeroProblem? [This line](https://github.com/NREL/rlmolecule/blob/20210407-run-config/examples/qed/optimize_qed.py#L43) probably isn't needed since self._config gets set here: https://github.com/NREL/rlmolecule/blob/e2d6375f3ae569aafa024920b2543b1388d3c7fe/rlmolecule/molecule/molecule_problem.py#L22

**Comment by pstjohn** [comment]
I'm fairly sure the base classes' __init__ should get called even if we don't provide an __init__ function.

**Comment by pstjohn** [comment]
I ran pycharm's code refactor on this, you might want to get in the habit of running some type of code linter (PEP8, etc) so we have a consistent style. I also deleted the `__init__` statement, it seems to work locally for me. But I am getting this error from line 110:
```
AttributeError: 'RunConfig' object has no attribute 'train_config'
```

**Comment by jlaw9** [comment]
Learned something new about Python today! Makes sense that it would inherit the __init__ function. And yes you're right, I'll make sure to use the PEP8 style. 

Just fixed the error. Sorry forgot that I hadn't pushed those changes

**Pull request merged**
